name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/login-action@v1
    - name: Build the Docker image
      run: docker build -t docker pull ghcr.io/zettayottaorg/task:latest .
    - uses: docker/build-push-action@v2
    - name: Build and push Docker image
      with:
          context: .
          push: true
          tags: ghcr.io/zettayottaorg/task:latest
