name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v2
    - name: Build the Docker image
      run: docker build -t docker pull ghcr.io/zettayottaorg/task:latest .
    - uses: docker/build-push-action@v2
    - name: publish
      run: docker pull ghcr.io/zettayottaorg/task:latest
